Write-Output "Getting all users"
Invoke-WebRequest -Method Get -Uri "http://localhost:3000/users"
Write-Output "Getting user fatcow"
Invoke-WebRequest -Method Get -Uri "http://localhost:3000/users/fatcow"
Write-Output "Getting nonexistent user fatcat"
Invoke-WebRequest -Method Get -Uri "http://localhost:3000/users/fatcat"